# Generated by Django 4.1 on 2023-05-21 15:11

import Qn.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="link",
            field=models.CharField(max_length=100, null=True, verbose_name="组织链接"),
        ),
        migrations.AlterField(
            model_name="question_answer",
            name="answer5",
            field=models.FileField(
                null=True, upload_to=Qn.models.answer_file_upload_to, verbose_name="回答5"
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=200, null=True, verbose_name="消息"),
                ),
                ("type", models.IntegerField(null=True, verbose_name="消息类型")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Qn.user"
                    ),
                ),
            ],
        ),
    ]
