# Generated by Django 4.1 on 2023-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization_create_questionnaire",
            name="necessary",
        ),
    ]
