# Generated by Django 4.1 on 2023-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="duration",
            field=models.IntegerField(null=True, verbose_name="问卷持续时间"),
        ),
    ]
