# Generated by Django 4.1 on 2023-05-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choices",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="organization_2_user",
            name="organization_id",
        ),
        migrations.RemoveField(
            model_name="organization_2_user",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="organization_create_questionnaire",
            name="organization_id",
        ),
        migrations.RemoveField(
            model_name="organization_create_questionnaire",
            name="questionnaire_id",
        ),
        migrations.RemoveField(
            model_name="question",
            name="questionnaire_id",
        ),
        migrations.RemoveField(
            model_name="question_answer",
            name="answer_sheet_id",
        ),
        migrations.RemoveField(
            model_name="question_answer",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="texts",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="user_create_questionnaire",
            name="questionnaire_id",
        ),
        migrations.RemoveField(
            model_name="user_create_questionnaire",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Answer_sheet",
        ),
        migrations.DeleteModel(
            name="Choices",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Organization_2_User",
        ),
        migrations.DeleteModel(
            name="Organization_create_Questionnaire",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Question_answer",
        ),
        migrations.DeleteModel(
            name="Questionnaire",
        ),
        migrations.DeleteModel(
            name="Texts",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="User_create_Questionnaire",
        ),
    ]
