# Generated by Django 4.1 on 2023-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0002_remove_organization_create_questionnaire_necessary"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="questionnaire_total_num",
            field=models.IntegerField(null=True, verbose_name="问卷题目总数"),
        ),
    ]
