# Generated by Django 4.1 on 2023-05-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="file",
        ),
    ]
