# Generated by Django 4.1 on 2023-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0005_rename_questionnaire_id_question_questionnaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="score",
            field=models.IntegerField(null=True, verbose_name="问题分数"),
        ),
    ]
