# Generated by Django 4.1 on 2023-05-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0006_alter_question_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer_sheet",
            old_name="questionnaire_id",
            new_name="questionnaire",
        ),
        migrations.RenameField(
            model_name="organization_2_user",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="organization_2_user",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="organization_create_questionnaire",
            old_name="organization_id",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="organization_create_questionnaire",
            old_name="questionnaire_id",
            new_name="questionnaire",
        ),
        migrations.RenameField(
            model_name="question_answer",
            old_name="answer_sheet_id",
            new_name="answer_sheet",
        ),
        migrations.RenameField(
            model_name="question_answer",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="user_create_questionnaire",
            old_name="questionnaire_id",
            new_name="questionnaire",
        ),
        migrations.RenameField(
            model_name="user_create_questionnaire",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="answer_sheet",
            name="answerer_id",
        ),
        migrations.AddField(
            model_name="answer_sheet",
            name="answerer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="Qn.user"
            ),
        ),
    ]
