# Generated by Django 4.1 on 2023-05-14 16:28

import Qn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Qn", "0006_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Qn.models.question_file_upload_to,
                verbose_name="问题图片",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Qn.models.question_file_upload_to,
                verbose_name="问题视频",
            ),
        ),
    ]
